=== ossf/osv-schema/tools/osv-linter/internal/checks/schema_generated.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/ossf/osv-schema/main/validation/schema.json",
  "title": "Open Source Vulnerability",
  "description": "A schema for describing a vulnerability in an open source package. See also https://ossf.github.io/osv-schema/",
  "type": "object",
  "properties": {
    "schema_version": {
      "type": "string"
    },
    "id": {
      "$ref": "#/$defs/prefix"
    },
    "modified": {
      "$ref": "#/$defs/timestamp"
    },
    "published": {
      "$ref": "#/$defs/timestamp"
    },
    "withdrawn": {
      "$ref": "#/$defs/timestamp"
    },
    "aliases": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "string"
      }
    },
    "related": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "upstream": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "summary": {
      "type": "string"
    },
    "details": {
      "type": "string"
    },
    "severity": {
      "$ref": "#/$defs/severity"
    },
    "affected": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "object",
        "properties": {
          "package": {
            "type": "object",
            "properties": {
              "ecosystem": {
                "$ref": "#/$defs/ecosystemWithSuffix"
              },
              "name": {
                "type": "string"
              },
              "purl": {
                "type": "string"
              }
            },
            "required": [
              "ecosystem",
              "name"
            ]
          },
          "severity": {
            "$ref": "#/$defs/severity"
          },
          "ranges": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "enum": [
                    "GIT",
                    "SEMVER",
                    "ECOSYSTEM"
                  ]
                },
                "repo": {
                  "type": "string"
                },
                "events": {
                  "title": "events must contain an introduced object and may contain fixed, last_affected or limit objects",
                  "type": "array",
                  "contains": {
                    "required": [
                      "introduced"
                    ]
                  },
                  "items": {
                    "type": "object",
                    "oneOf": [
                      {
                        "type": "object",
                        "properties": {
                          "introduced": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "introduced"
                        ]
                      },
                      {
                        "type": "object",
                        "properties": {
                          "fixed": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "fixed"
                        ]
                      },
                      {
                        "type": "object",
                        "properties": {
                          "last_affected": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "last_affected"
                        ]
                      },
                      {
                        "type": "object",
                        "properties": {
                          "limit": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "limit"
                        ]
                      }
                    ]
                  },
                  "minItems": 1
                },
                "database_specific": {
                  "type": "object"
                }
              },
              "allOf": [
                {
                  "title": "GIT ranges require a repo",
                  "if": {
                    "properties": {
                      "type": {
                        "const": "GIT"
                      }
                    }
                  },
                  "then": {
                    "required": [
                      "repo"
                    ]
                  }
                },
                {
                  "title": "GIT ranges must use full-length commit hashes",
                  "if": {
                    "properties": {
                      "type": {
                        "const": "GIT"
                      }
                    }
                  },
                  "then": {
                    "properties": {
                      "events": {
                        "items": {
                          "oneOf": [
                            {
                              "type": "object",
                              "properties": {
                                "introduced": {
                                  "type": "string",
                                  "pattern": "^(0|[a-f0-9]{40}|[a-f0-9]{64})$"
                                }
                              },
                              "required": [
                                "introduced"
                              ]
                            },
                            {
                              "type": "object",
                              "properties": {
                                "fixed": {
                                  "type": "string",
                                  "pattern": "^(0|[a-f0-9]{40}|[a-f0-9]{64})$"
                                }
                              },
                              "required": [
                                "fixed"
                              ]
                            },
                            {
                              "type": "object",
                              "properties": {
                                "last_affected": {
                                  "type": "string",
                                  "pattern": "^(0|[a-f0-9]{40}|[a-f0-9]{64})$"
                                }
                              },
                              "required": [
                                "last_affected"
                              ]
                            },
                            {
                              "type": "object",
                              "properties": {
                                "limit": {
                                  "type": "string",
                                  "pattern": "^(0|[a-f0-9]{40}|[a-f0-9]{64})$"
                                }
                              },
                              "required": [
                                "limit"
                              ]
                            }
                          ]
                        }
                      }
                    }
                  }
                },
                {
                  "title": "last_affected and fixed events are mutually exclusive",
                  "if": {
                    "properties": {
                      "events": {
                        "contains": {
                          "required": [
                            "last_affected"
                          ]
                        }
                      }
                    }
                  },
                  "then": {
                    "not": {
                      "properties": {
                        "events": {
                          "contains": {
                            "required": [
                              "fixed"
                            ]
                          }
                        }
                      }
                    }
                  }
                }
              ],
              "required": [
                "type",
                "events"
              ]
            }
          },
          "versions": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "ecosystem_specific": {
            "type": "object"
          },
          "database_specific": {
            "type": "object"
          }
        }
      }
    },
    "references": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "ADVISORY",
              "ARTICLE",
              "DETECTION",
              "DISCUSSION",
              "REPORT",
              "FIX",
              "INTRODUCED",
              "GIT",
              "PACKAGE",
              "EVIDENCE",
              "WEB"
            ]
          },
          "url": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": [
          "type",
          "url"
        ]
      }
    },
    "credits": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "contact": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "type": {
            "type": "string",
            "enum": [
              "FINDER",
              "REPORTER",
              "ANALYST",
              "COORDINATOR",
              "REMEDIATION_DEVELOPER",
              "REMEDIATION_REVIEWER",
              "REMEDIATION_VERIFIER",
              "TOOL",
              "SPONSOR",
              "OTHER"
            ]
          }
        },
        "required": [
          "name"
        ]
      }
    },
    "database_specific": {
      "type": "object"
    }
  },
  "required": [
    "id",
    "modified"
  ],
  "allOf": [
    {
      "if": {
        "required": [
          "severity"
        ]
      },
      "then": {
        "properties": {
          "affected": {
            "items": {
              "properties": {
                "severity": {
                  "type": "null"
                }
              }
            }
          }
        }
      }
    }
  ],
  "$defs": {
    "ecosystemName": {
      "type": "string",
      "title": "Currently supported ecosystems",
      "description": "These ecosystems are also documented at https://ossf.github.io/osv-schema/#affectedpackage-field",
      "enum": [
        "AlmaLinux",
        "Alpaquita",
        "Alpine",
        "Android",
        "Azure Linux",
        "BellSoft Hardened Containers",
        "Bioconductor",
        "Bitnami",
        "Chainguard",
        "CleanStart",
        "ConanCenter",
        "CRAN",
        "crates.io",
        "Debian",
        "Docker Hardened Images",
        "Echo",
        "FreeBSD",
        "GHC",
        "GitHub Actions",
        "Go",
        "Hackage",
        "Hex",
        "Julia",
        "Kubernetes",
        "Linux",
        "Mageia",
        "Maven",
        "MinimOS",
        "npm",
        "NuGet",
        "opam",
        "openEuler",
        "openSUSE",
        "OSS-Fuzz",
        "Packagist",
        "Photon OS",
        "Pub",
        "PyPI",
        "Red Hat",
        "Rocky Linux",
        "Root",
        "RubyGems",
        "SUSE",
        "SwiftURL",
        "TuxCare",
        "Ubuntu",
        "VSCode",
        "Wolfi"
      ]
    },
    "ecosystemSuffix": {
      "type": "string",
      "pattern": ":.+"
    },
    "ecosystemWithSuffix": {
      "type": "string",
      "title": "Currently supported ecosystems",
      "description": "These ecosystems are also documented at https://ossf.github.io/osv-schema/#affectedpackage-field",
      "pattern": "^(AlmaLinux|Alpaquita|Alpine|Android|Azure Linux|BellSoft Hardened Containers|Bioconductor|Bitnami|Chainguard|CleanStart|ConanCenter|CRAN|crates\\.io|Debian|Docker Hardened Images|Echo|FreeBSD|GHC|GitHub Actions|Go|Hackage|Hex|Julia|Kubernetes|Linux|Mageia|Maven|MinimOS|npm|NuGet|opam|openEuler|openSUSE|OSS-Fuzz|Packagist|Photon OS|Pub|PyPI|Red Hat|Rocky Linux|Root|RubyGems|SUSE|SwiftURL|TuxCare|Ubuntu|VSCode|Wolfi|GIT)(:.+)?$"
    },
    "prefix": {
      "type": "string",
      "title": "Currently supported home database identifier prefixes",
      "description": "These home databases are also documented at https://ossf.github.io/osv-schema/#id-modified-fields",
      "pattern": "^(x_|(ASB-A|PUB-A|ALPINE|ALSA|ALBA|ALEA|AZL|BELL|BIT|CGA|CLEANSTART|CLSA|CURL|CVE|DEBIAN|DHI|DRUPAL|DSA|DLA|ELA|DTSA|ECHO|EEF|FreeBSD|GHSA|GO|GSD|HSEC|JLSEC|KUBE|LBSEC|LSN|MAL|MINI|MGASA|OESA|OSEC|OSV|openSUSE-SU|PHSA|PSF|PYSEC|RHBA|RHEA|RHSA|RLSA|RXSA|RSEC|ROOT|RUSTSEC|SUSE-[SRFO]U|UBUNTU|USN|V8)-)"
    },
    "severity": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "CVSS_V2",
              "CVSS_V3",
              "CVSS_V4",
              "Ubuntu"
            ]
          },
          "score": {
            "type": "string"
          },
          "source": {
            "type": "string",
            "enum": [
              "NVD",
              "CNA",
              "SELF"
            ]
          }
        },
        "allOf": [
          {
            "if": {
              "properties": {
                "type": {
                  "const": "CVSS_V2"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "pattern": "^((AV:[NAL]|AC:[LMH]|Au:[MSN]|[CIA]:[NPC]|E:(U|POC|F|H|ND)|RL:(OF|TF|W|U|ND)|RC:(UC|UR|C|ND)|CDP:(N|L|LM|MH|H|ND)|TD:(N|L|M|H|ND)|[CIA]R:(L|M|H|ND))/)*(AV:[NAL]|AC:[LMH]|Au:[MSN]|[CIA]:[NPC]|E:(U|POC|F|H|ND)|RL:(OF|TF|W|U|ND)|RC:(UC|UR|C|ND)|CDP:(N|L|LM|MH|H|ND)|TD:(N|L|M|H|ND)|[CIA]R:(L|M|H|ND))$"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "const": "CVSS_V3"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "pattern": "^CVSS:3[.][01]/((AV:[NALP]|AC:[LH]|PR:[NLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])/)*(AV:[NALP]|AC:[LH]|PR:[NLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])$"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "const": "CVSS_V4"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "pattern": "^CVSS:4[.]0/AV:[NALP]/AC:[LH]/AT:[NP]/PR:[NLH]/UI:[NPA]/VC:[HLN]/VI:[HLN]/VA:[HLN]/SC:[HLN]/SI:[HLN]/SA:[HLN](/E:[XAPU])?(/CR:[XHML])?(/IR:[XHML])?(/AR:[XHML])?(/MAV:[XNALP])?(/MAC:[XLH])?(/MAT:[XNP])?(/MPR:[XNLH])?(/MUI:[XNPA])?(/MVC:[XNLH])?(/MVI:[XNLH])?(/MVA:[XNLH])?(/MSC:[XNLH])?(/MSI:[XNLHS])?(/MSA:[XNLHS])?(/S:[XNP])?(/AU:[XNY])?(/R:[XAUI])?(/V:[XDC])?(/RE:[XLMH])?(/U:(X|Clear|Green|Amber|Red))?$"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "const": "Ubuntu"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "enum": [
                    "negligible",
                    "low",
                    "medium",
                    "high",
                    "critical"
                  ]
                }
              }
            }
          }
        ],
        "required": [
          "type",
          "score"
        ]
      }
    },
    "timestamp": {
      "type": "string",
      "format": "date-time",
      "pattern": "[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+)?Z"
    }
  },
  "additionalProperties": false
}

=== ossf/osv-schema/tools/ghsa/testdata/equals_with_patch.osv.json
{
  "schema_version": "1.5.0",
  "id": "GHSA-fhjf-83wg-r2j9",
  "aliases": [
    "CVE-2019-10746"
  ],
  "published": "2019-08-27T17:42:33Z",
  "modified": "2021-07-27T21:26:01Z",
  "summary": "Prototype Pollution in mixin-deep",
  "details": "Versions of `mixin-deep` prior to 2.0.1 or 1.3.2 are vulnerable to Prototype Pollution. The `mixinDeep` function fails to validate which Object properties it updates. This allows attackers to modify the prototype of Object, causing the addition or modification of an existing property on all objects.\n\n\n\n\n## Recommendation\n\nIf you are using `mixin-deep` 2.x, upgrade to version 2.0.1 or later.\nIf you are using `mixin-deep` 1.x, upgrade to version 1.3.2 or later.",
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-10746"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-fhjf-83wg-r2j9"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "npm",
        "name": "mixin-deep"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "introduced": "2.0.0"
            },
            {
              "fixed": "2.0.1"
            },
            {
              "fixed": "1.3.2"
            }
          ]
        }
      ],
      "versions": [],
      "database_specific": {
        "ghsa": "https://github.com/advisories/GHSA-fhjf-83wg-r2j9",
        "cwes": [
          {
            "cweId": "CWE-88",
            "description": "The software constructs a string for a command to executed by a separate component in another control sphere, but it does not properly delimit the intended arguments, options, or switches within that command string.",
            "name": "Improper Neutralization of Argument Delimiters in a Command ('Argument Injection')"
          }
        ]
      }
    }
  ]
}

=== ossf/osv-schema/tools/ghsa/testdata/pypi_normalize.osv.json
{
  "schema_version": "1.5.0",
  "id": "GHSA-p44j-xrqg-4xrr",
  "aliases": [
    "CVE-2021-21337"
  ],
  "published": "2021-03-08T21:06:23Z",
  "modified": "2021-06-03T13:49:55Z",
  "summary": "URL Redirection to Untrusted Site ('Open Redirect') in Products.PluggableAuthService",
  "details": "### Impact\n_What kind of vulnerability is it? Who is impacted?_\n\nOpen redirect vulnerability - a maliciously crafted link to the login form and login functionality could redirect the browser to a different website.\n\n### Patches\n_Has the problem been patched? What versions should users upgrade to?_\n\nThe problem has been fixed in version 2.6.1. Depending on how you have installed Products.PluggableAuthService, you should change the buildout version pin to `2.6.1`  and re-run the buildout, or if you used `pip` simply do `pip install \"Products.PluggableAuthService>=2.6.1\"`\n\n### Workarounds\n_Is there a way for users to fix or remediate the vulnerability without upgrading?_\n\nThere is no workaround. Users are encouraged to upgrade.\n\n### References\n_Are there any links users can visit to find out more?_\n\n- [GHSA-p44j-xrqg-4xrr](https://github.com/zopefoundation/Products.PluggableAuthService/security/advisories/GHSA-p44j-xrqg-4xrr)\n- [Products.PluggableAuthService on PyPI](https://pypi.org/project/Products.PluggableAuthService/)\n- [OWASP page on open redirects](https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html)\n\n### For more information\nIf you have any questions or comments about this advisory:\n* Open an issue in the [Products.PluggableAuthService issue tracker](https://github.com/zopefoundation/Products.PluggableAuthService/issues)\n* Email us at [security@plone.org](mailto:security@plone.org)",
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/zopefoundation/Products.PluggableAuthService/security/advisories/GHSA-p44j-xrqg-4xrr"
    },
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-21337"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-p44j-xrqg-4xrr"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "products-pluggableauthservice"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2.6.1"
            }
          ]
        }
      ],
      "versions": [],
      "database_specific": {
        "ghsa": "https://github.com/advisories/GHSA-p44j-xrqg-4xrr",
        "cwes": [
          {
            "cweId": "CWE-601",
            "description": "A web application accepts a user-controlled input that specifies a link to an external site, and uses that link in a Redirect. This simplifies phishing attacks.",
            "name": "URL Redirection to Untrusted Site ('Open Redirect')"
          }
        ]
      }
    }
  ]
}

=== ossf/osv-schema/tools/ghsa/testdata/npm_greater_than.osv.json
{
  "id": "GHSA-mhpp-875w-9cpv",
  "aliases": [
    "CVE-2016-10707"
  ],
  "published": "2018-01-22T13:32:42Z",
  "modified": "2021-09-15T20:10:34Z",
  "summary": "Denial of Service in jquery",
  "details": "Affected versions of `jquery` use a lowercasing logic on attribute names. When given a boolean attribute with a name that contains uppercase characters, `jquery` enters into an infinite recursion loop, exceeding the call stack limit, and resulting in a denial of service condition.\n\n\n## Recommendation\n\nUpdate to version 3.0.0 or later.",
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2016-10707"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-mhpp-875w-9cpv"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "npm",
        "name": "jquery"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "2.1.1-0"
            },
            {
              "fixed": "3.0.0"
            }
          ]
        }
      ],
      "versions": [],
      "database_specific": {
        "ghsa": "https://github.com/advisories/GHSA-mhpp-875w-9cpv",
        "cvss": {
          "score": 7.5,
          "vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
        },
        "cwes": [
          {
            "cweId": "CWE-400",
            "description": "The software does not properly control the allocation and maintenance of a limited resource, thereby enabling an actor to influence the amount of resources consumed, eventually leading to the exhaustion of available resources.",
            "name": "Uncontrolled Resource Consumption"
          }
        ]
      }
    }
  ]
}

=== ossf/osv-schema/tools/osv-linter/testdata/wildcard-package.json
{
  "modified": "2026-06-10T00:00:00Z",
  "published": "2026-06-10T00:00:00Z",
  "schema_version": "1.5.0",
  "id": "CVE-2026-99999",
  "summary": "Ecosystem wildcard test",
  "details": "This is a test case for a wildcard package name.",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "*"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ]
}

=== ossf/osv-schema/tools/vuxml/testdata/OSV/UBUNTU-CVE-2025-3454.json
{
  "schema_version": "1.6.3",
  "id": "UBUNTU-CVE-2025-3454",
  "details": "[Unknown description]",
  "aliases": [],
  "related": [
    "CVE-2025-3454"
  ],
  "published": "2025-04-28T00:00:00Z",
  "modified": "2025-04-29T16:36:00Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:Pro:16.04:LTS",
        "name": "grafana",
        "purl": "pkg:deb/ubuntu/grafana@2.6.0+dfsg-1?arch=source&distro=esm-apps/xenial"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            }
          ]
        }
      ],
      "versions": [
        "2.6.0+dfsg-1"
      ],
      "ecosystem_specific": {
        "ubuntu_priority": "medium"
      }
    }
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2025-3454"
    },
    {
      "type": "REPORT",
      "url": "https://www.cve.org/CVERecord?id=CVE-2025-3454"
    }
  ]
}
