=== ossf/osv-schema/tools/osv-linter/internal/checks/schema_generated.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/ossf/osv-schema/main/validation/schema.json",
  "title": "Open Source Vulnerability",
  "description": "A schema for describing a vulnerability in an open source package. See also https://ossf.github.io/osv-schema/",
  "type": "object",
  "properties": {
    "schema_version": {
      "type": "string"
    },
    "id": {
      "$ref": "#/$defs/prefix"
    },
    "modified": {
      "$ref": "#/$defs/timestamp"
    },
    "published": {
      "$ref": "#/$defs/timestamp"
    },
    "withdrawn": {
      "$ref": "#/$defs/timestamp"
    },
    "aliases": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "string"
      }
    },
    "related": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "upstream": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "summary": {
      "type": "string"
    },
    "details": {
      "type": "string"
    },
    "severity": {
      "$ref": "#/$defs/severity"
    },
    "affected": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "object",
        "properties": {
          "package": {
            "type": "object",
            "properties": {
              "ecosystem": {
                "$ref": "#/$defs/ecosystemWithSuffix"
              },
              "name": {
                "type": "string"
              },
              "purl": {
                "type": "string"
              }
            },
            "required": [
              "ecosystem",
              "name"
            ]
          },
          "severity": {
            "$ref": "#/$defs/severity"
          },
          "ranges": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "enum": [
                    "GIT",
                    "SEMVER",
                    "ECOSYSTEM"
                  ]
                },
                "repo": {
                  "type": "string"
                },
                "events": {
                  "title": "events must contain an introduced object and may contain fixed, last_affected or limit objects",
                  "type": "array",
                  "contains": {
                    "required": [
                      "introduced"
                    ]
                  },
                  "items": {
                    "type": "object",
                    "oneOf": [
                      {
                        "type": "object",
                        "properties": {
                          "introduced": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "introduced"
                        ]
                      },
                      {
                        "type": "object",
                        "properties": {
                          "fixed": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "fixed"
                        ]
                      },
                      {
                        "type": "object",
                        "properties": {
                          "last_affected": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "last_affected"
                        ]
                      },
                      {
                        "type": "object",
                        "properties": {
                          "limit": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "limit"
                        ]
                      }
                    ]
                  },
                  "minItems": 1
                },
                "database_specific": {
                  "type": "object"
                }
              },
              "allOf": [
                {
                  "title": "GIT ranges require a repo",
                  "if": {
                    "properties": {
                      "type": {
                        "const": "GIT"
                      }
                    }
                  },
                  "then": {
                    "required": [
                      "repo"
                    ]
                  }
                },
                {
                  "title": "GIT ranges must use full-length commit hashes",
                  "if": {
                    "properties": {
                      "type": {
                        "const": "GIT"
                      }
                    }
                  },
                  "then": {
                    "properties": {
                      "events": {
                        "items": {
                          "oneOf": [
                            {
                              "type": "object",
                              "properties": {
                                "introduced": {
                                  "type": "string",
                                  "pattern": "^(0|[a-f0-9]{40}|[a-f0-9]{64})$"
                                }
                              },
                              "required": [
                                "introduced"
                              ]
                            },
                            {
                              "type": "object",
                              "properties": {
                                "fixed": {
                                  "type": "string",
                                  "pattern": "^(0|[a-f0-9]{40}|[a-f0-9]{64})$"
                                }
                              },
                              "required": [
                                "fixed"
                              ]
                            },
                            {
                              "type": "object",
                              "properties": {
                                "last_affected": {
                                  "type": "string",
                                  "pattern": "^(0|[a-f0-9]{40}|[a-f0-9]{64})$"
                                }
                              },
                              "required": [
                                "last_affected"
                              ]
                            },
                            {
                              "type": "object",
                              "properties": {
                                "limit": {
                                  "type": "string",
                                  "pattern": "^(0|[a-f0-9]{40}|[a-f0-9]{64})$"
                                }
                              },
                              "required": [
                                "limit"
                              ]
                            }
                          ]
                        }
                      }
                    }
                  }
                },
                {
                  "title": "last_affected and fixed events are mutually exclusive",
                  "if": {
                    "properties": {
                      "events": {
                        "contains": {
                          "required": [
                            "last_affected"
                          ]
                        }
                      }
                    }
                  },
                  "then": {
                    "not": {
                      "properties": {
                        "events": {
                          "contains": {
                            "required": [
                              "fixed"
                            ]
                          }
                        }
                      }
                    }
                  }
                }
              ],
              "required": [
                "type",
                "events"
              ]
            }
          },
          "versions": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "ecosystem_specific": {
            "type": "object"
          },
          "database_specific": {
            "type": "object"
          }
        }
      }
    },
    "references": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "ADVISORY",
              "ARTICLE",
              "DETECTION",
              "DISCUSSION",
              "REPORT",
              "FIX",
              "INTRODUCED",
              "GIT",
              "PACKAGE",
              "EVIDENCE",
              "WEB"
            ]
          },
          "url": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": [
          "type",
          "url"
        ]
      }
    },
    "credits": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "contact": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "type": {
            "type": "string",
            "enum": [
              "FINDER",
              "REPORTER",
              "ANALYST",
              "COORDINATOR",
              "REMEDIATION_DEVELOPER",
              "REMEDIATION_REVIEWER",
              "REMEDIATION_VERIFIER",
              "TOOL",
              "SPONSOR",
              "OTHER"
            ]
          }
        },
        "required": [
          "name"
        ]
      }
    },
    "database_specific": {
      "type": "object"
    }
  },
  "required": [
    "id",
    "modified"
  ],
  "allOf": [
    {
      "if": {
        "required": [
          "severity"
        ]
      },
      "then": {
        "properties": {
          "affected": {
            "items": {
              "properties": {
                "severity": {
                  "type": "null"
                }
              }
            }
          }
        }
      }
    }
  ],
  "$defs": {
    "ecosystemName": {
      "type": "string",
      "title": "Currently supported ecosystems",
      "description": "These ecosystems are also documented at https://ossf.github.io/osv-schema/#affectedpackage-field",
      "enum": [
        "AlmaLinux",
        "Alpaquita",
        "Alpine",
        "Android",
        "Azure Linux",
        "BellSoft Hardened Containers",
        "Bioconductor",
        "Bitnami",
        "Chainguard",
        "CleanStart",
        "ConanCenter",
        "CRAN",
        "crates.io",
        "Debian",
        "Docker Hardened Images",
        "Echo",
        "FreeBSD",
        "GHC",
        "GitHub Actions",
        "Go",
        "Hackage",
        "Hex",
        "Julia",
        "Kubernetes",
        "Linux",
        "Mageia",
        "Maven",
        "MinimOS",
        "npm",
        "NuGet",
        "opam",
        "openEuler",
        "openSUSE",
        "OSS-Fuzz",
        "Packagist",
        "Photon OS",
        "Pub",
        "PyPI",
        "Red Hat",
        "Rocky Linux",
        "Root",
        "RubyGems",
        "SUSE",
        "SwiftURL",
        "TuxCare",
        "Ubuntu",
        "VSCode",
        "Wolfi"
      ]
    },
    "ecosystemSuffix": {
      "type": "string",
      "pattern": ":.+"
    },
    "ecosystemWithSuffix": {
      "type": "string",
      "title": "Currently supported ecosystems",
      "description": "These ecosystems are also documented at https://ossf.github.io/osv-schema/#affectedpackage-field",
      "pattern": "^(AlmaLinux|Alpaquita|Alpine|Android|Azure Linux|BellSoft Hardened Containers|Bioconductor|Bitnami|Chainguard|CleanStart|ConanCenter|CRAN|crates\\.io|Debian|Docker Hardened Images|Echo|FreeBSD|GHC|GitHub Actions|Go|Hackage|Hex|Julia|Kubernetes|Linux|Mageia|Maven|MinimOS|npm|NuGet|opam|openEuler|openSUSE|OSS-Fuzz|Packagist|Photon OS|Pub|PyPI|Red Hat|Rocky Linux|Root|RubyGems|SUSE|SwiftURL|TuxCare|Ubuntu|VSCode|Wolfi|GIT)(:.+)?$"
    },
    "prefix": {
      "type": "string",
      "title": "Currently supported home database identifier prefixes",
      "description": "These home databases are also documented at https://ossf.github.io/osv-schema/#id-modified-fields",
      "pattern": "^(x_|(ASB-A|PUB-A|ALPINE|ALSA|ALBA|ALEA|AZL|BELL|BIT|CGA|CLEANSTART|CLSA|CURL|CVE|DEBIAN|DHI|DRUPAL|DSA|DLA|ELA|DTSA|ECHO|EEF|FreeBSD|GHSA|GO|GSD|HSEC|JLSEC|KUBE|LBSEC|LSN|MAL|MINI|MGASA|OESA|OSEC|OSV|openSUSE-SU|PHSA|PSF|PYSEC|RHBA|RHEA|RHSA|RLSA|RXSA|RSEC|ROOT|RUSTSEC|SUSE-[SRFO]U|UBUNTU|USN|V8)-)"
    },
    "severity": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "CVSS_V2",
              "CVSS_V3",
              "CVSS_V4",
              "Ubuntu"
            ]
          },
          "score": {
            "type": "string"
          },
          "source": {
            "type": "string",
            "enum": [
              "NVD",
              "CNA",
              "SELF"
            ]
          }
        },
        "allOf": [
          {
            "if": {
              "properties": {
                "type": {
                  "const": "CVSS_V2"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "pattern": "^((AV:[NAL]|AC:[LMH]|Au:[MSN]|[CIA]:[NPC]|E:(U|POC|F|H|ND)|RL:(OF|TF|W|U|ND)|RC:(UC|UR|C|ND)|CDP:(N|L|LM|MH|H|ND)|TD:(N|L|M|H|ND)|[CIA]R:(L|M|H|ND))/)*(AV:[NAL]|AC:[LMH]|Au:[MSN]|[CIA]:[NPC]|E:(U|POC|F|H|ND)|RL:(OF|TF|W|U|ND)|RC:(UC|UR|C|ND)|CDP:(N|L|LM|MH|H|ND)|TD:(N|L|M|H|ND)|[CIA]R:(L|M|H|ND))$"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "const": "CVSS_V3"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "pattern": "^CVSS:3[.][01]/((AV:[NALP]|AC:[LH]|PR:[NLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])/)*(AV:[NALP]|AC:[LH]|PR:[NLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])$"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "const": "CVSS_V4"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "pattern": "^CVSS:4[.]0/AV:[NALP]/AC:[LH]/AT:[NP]/PR:[NLH]/UI:[NPA]/VC:[HLN]/VI:[HLN]/VA:[HLN]/SC:[HLN]/SI:[HLN]/SA:[HLN](/E:[XAPU])?(/CR:[XHML])?(/IR:[XHML])?(/AR:[XHML])?(/MAV:[XNALP])?(/MAC:[XLH])?(/MAT:[XNP])?(/MPR:[XNLH])?(/MUI:[XNPA])?(/MVC:[XNLH])?(/MVI:[XNLH])?(/MVA:[XNLH])?(/MSC:[XNLH])?(/MSI:[XNLHS])?(/MSA:[XNLHS])?(/S:[XNP])?(/AU:[XNY])?(/R:[XAUI])?(/V:[XDC])?(/RE:[XLMH])?(/U:(X|Clear|Green|Amber|Red))?$"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "const": "Ubuntu"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "enum": [
                    "negligible",
                    "low",
                    "medium",
                    "high",
                    "critical"
                  ]
                }
              }
            }
          }
        ],
        "required": [
          "type",
          "score"
        ]
      }
    },
    "timestamp": {
      "type": "string",
      "format": "date-time",
      "pattern": "[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+)?Z"
    }
  },
  "additionalProperties": false
}

=== ossf/osv-schema/tools/ghsa/testdata/full_ranges.osv.json
{
  "schema_version": "1.5.0",
  "id": "GHSA-mr95-9rr4-668f",
  "aliases": [
    "CVE-2018-16115"
  ],
  "published": "2018-10-22T20:44:26Z",
  "modified": "2021-09-15T20:58:47Z",
  "summary": "High severity vulnerability that affects com.typesafe.akka:akka-actor_2.11 and com.typesafe.akka:akka-actor_2.12",
  "details": "Lightbend Akka 2.5.x before 2.5.16 allows message disclosure and modification because of an RNG error. A random number generator is used in Akka Remoting for TLS (both classic and Artery Remoting). Akka allows configuration of custom random number generators. For historical reasons, Akka included the AES128CounterSecureRNG and AES256CounterSecureRNG random number generators. The implementations had a bug that caused the generated numbers to be repeated after only a few bytes. The custom RNG implementations were not configured by default but examples in the documentation showed (and therefore implicitly recommended) using the custom ones. This can be used by an attacker to compromise the communication if these random number generators are enabled in configuration. It would be possible to eavesdrop, replay, or modify the messages sent with Akka Remoting/Cluster.",
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2018-16115"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-mr95-9rr4-668f"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "Maven",
        "name": "com.typesafe.akka:akka-actor_2.12"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "2.5.0"
            },
            {
              "fixed": "2.5.16"
            }
          ]
        }
      ],
      "versions": [],
      "database_specific": {
        "ghsa": "https://github.com/advisories/GHSA-mr95-9rr4-668f",
        "cwes": [
          {
            "cweId": "CWE-338",
            "description": "The product uses a Pseudo-Random Number Generator (PRNG) in a security context, but the PRNG's algorithm is not cryptographically strong.",
            "name": "Use of Cryptographically Weak Pseudo-Random Number Generator (PRNG)"
          }
        ]
      }
    },
    {
      "package": {
        "ecosystem": "Maven",
        "name": "com.typesafe.akka:akka-actor_2.11"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "2.5.0"
            },
            {
              "fixed": "2.5.16"
            }
          ]
        }
      ],
      "versions": [],
      "database_specific": {
        "ghsa": "https://github.com/advisories/GHSA-mr95-9rr4-668f",
        "cwes": [
          {
            "cweId": "CWE-338",
            "description": "The product uses a Pseudo-Random Number Generator (PRNG) in a security context, but the PRNG's algorithm is not cryptographically strong.",
            "name": "Use of Cryptographically Weak Pseudo-Random Number Generator (PRNG)"
          }
        ]
      }
    }
  ]
}

=== ossf/osv-schema/tools/vuxml/testdata/VUXML/CVE-2025-29087.json
{
    "schema_version": "1.2.0",
    "id": "409206f6-25e6-11f0-9360-b42e991fc52e",
    "modified": "2025-04-30T00:00:00Z",
    "published": "2025-04-30T00:00:00Z",
    "summary": "sqlite -- integer overflow",
    "details": "\n\t\n\tcve@mitre.org reports:\n\t\n\t\n\tIn SQLite 3.44.0 through 3.49.0 before 3.49.1, the\n\tconcat_ws() SQL function can cause memory to be written\n\tbeyond the end of a malloc-allocated buffer. If the\n\tseparator argument is attacker-controlled and has a large\n\tstring (e.g., 2MB or more), an integer overflow occurs in\n\tcalculating the size of the result buffer, and thus malloc\n\tmay not allocate enough memory.\n\t\n\t\n\t\n    \n    ",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://api.osv.dev/v1/vulns/CVE-2025-29087"
        },
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2025-29087"
        }
    ],
    "affected": [
        {
            "package": {
                "ecosystem": "FreeBSD:ports",
                "name": "sqlite"
            },
            "ranges": [
                {
                    "type": "SEMVER",
                    "events": [
                        {
                            "fixed": "3.49.1"
                        },
                        {
                            "introduced": "0"
                        }
                    ]
                }
            ]
        }
    ],
    "database_specific": {
        "discovery": "2025-04-07T00:00:00Z"
    }
}

=== ossf/osv-schema/tools/ghsa/testdata/less_than_equals_no_patch.osv.json
{
  "schema_version": "1.5.0",
  "id": "GHSA-jvf4-g24p-2qgw",
  "aliases": [
    "CVE-2020-7738"
  ],
  "published": "2021-05-10T18:37:34Z",
  "modified": "2021-05-10T18:37:34Z",
  "summary": "Arbitrary Code Execution in shiba",
  "details": "\"All versions of package shiba are vulnerable to Arbitrary Code Execution due to the default usage of the function load() of the package js-yaml instead of its secure replacement , safeLoad().\"",
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-7738"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-jvf4-g24p-2qgw"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "npm",
        "name": "shiba"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            }
          ]
        }
      ],
      "versions": [],
      "database_specific": {
        "ghsa": "https://github.com/advisories/GHSA-jvf4-g24p-2qgw",
        "cwes": [
          {
            "cweId": "CWE-94",
            "description": "The software constructs all or part of a code segment using externally-influenced input from an upstream component, but it does not neutralize or incorrectly neutralizes special elements that could modify the syntax or behavior of the intended code segment.",
            "name": "Improper Control of Generation of Code ('Code Injection')"
          }
        ]
      }
    }
  ]
}

=== ossf/osv-schema/tools/ghsa/testdata/withdrawn.osv.json
{
  "schema_version": "1.5.0",
  "id": "GHSA-35c4-f3rq-f9g3",
  "aliases": [
    "CVE-2015-3227"
  ],
  "published": "2018-09-17T21:57:23Z",
  "modified": "2019-07-03T21:02:03Z",
  "withdrawn": "2018-10-11T17:29:49Z",
  "summary": "Moderate severity vulnerability that affects activesupport",
  "details": "Withdrawn, accidental duplicate publish.\r\n\r\nThe (1) jdom.rb and (2) rexml.rb components in Active Support in Ruby on Rails before 4.1.11 and 4.2.x before 4.2.2, when JDOM or REXML is enabled, allow remote attackers to cause a denial of service (SystemStackError) via a large XML document depth.",
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2015-3227"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-35c4-f3rq-f9g3"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "RubyGems",
        "name": "activesupport"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "3.2.0"
            },
            {
              "fixed": "3.2.22"
            },
            {
              "introduced": "4.2.0"
            },
            {
              "fixed": "4.2.2"
            },
            {
              "introduced": "4.0.0"
            },
            {
              "fixed": "4.1.11"
            }
          ]
        }
      ],
      "versions": [],
      "database_specific": {
        "ghsa": "https://github.com/advisories/GHSA-35c4-f3rq-f9g3",
        "cwes": []
      }
    }
  ]
}

=== ossf/osv-schema/tools/osv-linter/test_data/GO-2020-0001.json
{"schema_version":"1.3.1","id":"GO-2020-0001","modified":"2024-05-20T16:03:47Z","published":"2021-04-14T20:04:52Z","aliases":["CVE-2020-36567","GHSA-6vm3-jj99-7229"],"summary":"Arbitrary log line injection in github.com/gin-gonic/gin","details":"The default Formatter for the Logger middleware (LoggerConfig.Formatter), which is included in the Default engine, allows attackers to inject arbitrary log entries by manipulating the request path.","affected":[{"package":{"name":"github.com/gin-gonic/gin","ecosystem":"Go"},"ranges":[{"type":"SEMVER","events":[{"introduced":"0"},{"fixed":"1.6.0"}]}],"ecosystem_specific":{"imports":[{"path":"github.com/gin-gonic/gin","symbols":["Default","Logger","LoggerWithConfig","LoggerWithFormatter","LoggerWithWriter"]}]}}],"references":[{"type":"FIX","url":"https://github.com/gin-gonic/gin/pull/2237"},{"type":"FIX","url":"https://github.com/gin-gonic/gin/commit/a71af9c144f9579f6dbe945341c1df37aaf09c0d"}],"credits":[{"name":"@thinkerou \u003cthinkerou@gmail.com\u003e"}],"database_specific":{"url":"https://pkg.go.dev/vuln/GO-2020-0001","review_status":"REVIEWED"}}

=== ossf/osv-schema/tools/ghsa/testdata/maven_greater_than.osv.json
{
  "id": "GHSA-76mp-659p-rw65",
  "aliases": [
    "CVE-2021-32620"
  ],
  "published": "2021-05-18T18:36:21Z",
  "modified": "2021-06-08T17:00:19Z",
  "summary": "Users registered with email verification can self re-activate their disabled accounts",
  "details": "### Impact\nA user disabled on a wiki using email verification for registration can re-activate himself by using the activation link provided for his registration. \n\n### Patches\nThe problem has been patched in the following versions of XWiki: 11.10.13,  12.6.7, 12.10.2, 13.0.\n\n### Workarounds\nIt's possible to workaround the issue by resetting the `validkey` property of the disabled XWiki users. This can be done by editing the user profile with object editor.\n\n### References\nhttps://jira.xwiki.org/browse/XWIKI-17942\n\n### For more information\nIf you have any questions or comments about this advisory:\n* Open an issue in [Jira](http://jira.xwiki.org)\n* Email us at [Security mailing-list](mailto:security@xwiki.org)\n",
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/xwiki/xwiki-platform/security/advisories/GHSA-76mp-659p-rw65"
    },
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-32620"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-76mp-659p-rw65"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "Maven",
        "name": "org.xwiki.commons:xwiki-commons-core"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "12.10.0"
            },
            {
              "fixed": "12.10.2"
            },
            {
              "introduced": "12.0"
            },
            {
              "fixed": "12.6.7"
            },
            {
              "introduced": "11.6.1"
            },
            {
              "fixed": "11.10.13"
            }
          ]
        }
      ],
      "versions": [],
      "database_specific": {
        "ghsa": "https://github.com/advisories/GHSA-76mp-659p-rw65",
        "cvss": {
          "score": 8.8,
          "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H"
        },
        "cwes": [
          {
            "cweId": "CWE-285",
            "description": "The software does not perform or incorrectly performs an authorization check when an actor attempts to access a resource or perform an action.",
            "name": "Improper Authorization"
          }
        ]
      }
    }
  ]
}
