=== ossf/osv-schema/tools/osv-linter/internal/checks/schema_generated.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/ossf/osv-schema/main/validation/schema.json",
  "title": "Open Source Vulnerability",
  "description": "A schema for describing a vulnerability in an open source package. See also https://ossf.github.io/osv-schema/",
  "type": "object",
  "properties": {
    "schema_version": {
      "type": "string"
    },
    "id": {
      "$ref": "#/$defs/prefix"
    },
    "modified": {
      "$ref": "#/$defs/timestamp"
    },
    "published": {
      "$ref": "#/$defs/timestamp"
    },
    "withdrawn": {
      "$ref": "#/$defs/timestamp"
    },
    "aliases": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "string"
      }
    },
    "related": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "upstream": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "summary": {
      "type": "string"
    },
    "details": {
      "type": "string"
    },
    "severity": {
      "$ref": "#/$defs/severity"
    },
    "affected": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "object",
        "properties": {
          "package": {
            "type": "object",
            "properties": {
              "ecosystem": {
                "$ref": "#/$defs/ecosystemWithSuffix"
              },
              "name": {
                "type": "string"
              },
              "purl": {
                "type": "string"
              }
            },
            "required": [
              "ecosystem",
              "name"
            ]
          },
          "severity": {
            "$ref": "#/$defs/severity"
          },
          "ranges": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "enum": [
                    "GIT",
                    "SEMVER",
                    "ECOSYSTEM"
                  ]
                },
                "repo": {
                  "type": "string"
                },
                "events": {
                  "title": "events must contain an introduced object and may contain fixed, last_affected or limit objects",
                  "type": "array",
                  "contains": {
                    "required": [
                      "introduced"
                    ]
                  },
                  "items": {
                    "type": "object",
                    "oneOf": [
                      {
                        "type": "object",
                        "properties": {
                          "introduced": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "introduced"
                        ]
                      },
                      {
                        "type": "object",
                        "properties": {
                          "fixed": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "fixed"
                        ]
                      },
                      {
                        "type": "object",
                        "properties": {
                          "last_affected": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "last_affected"
                        ]
                      },
                      {
                        "type": "object",
                        "properties": {
                          "limit": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "limit"
                        ]
                      }
                    ]
                  },
                  "minItems": 1
                },
                "database_specific": {
                  "type": "object"
                }
              },
              "allOf": [
                {
                  "title": "GIT ranges require a repo",
                  "if": {
                    "properties": {
                      "type": {
                        "const": "GIT"
                      }
                    }
                  },
                  "then": {
                    "required": [
                      "repo"
                    ]
                  }
                },
                {
                  "title": "GIT ranges must use full-length commit hashes",
                  "if": {
                    "properties": {
                      "type": {
                        "const": "GIT"
                      }
                    }
                  },
                  "then": {
                    "properties": {
                      "events": {
                        "items": {
                          "oneOf": [
                            {
                              "type": "object",
                              "properties": {
                                "introduced": {
                                  "type": "string",
                                  "pattern": "^(0|[a-f0-9]{40}|[a-f0-9]{64})$"
                                }
                              },
                              "required": [
                                "introduced"
                              ]
                            },
                            {
                              "type": "object",
                              "properties": {
                                "fixed": {
                                  "type": "string",
                                  "pattern": "^(0|[a-f0-9]{40}|[a-f0-9]{64})$"
                                }
                              },
                              "required": [
                                "fixed"
                              ]
                            },
                            {
                              "type": "object",
                              "properties": {
                                "last_affected": {
                                  "type": "string",
                                  "pattern": "^(0|[a-f0-9]{40}|[a-f0-9]{64})$"
                                }
                              },
                              "required": [
                                "last_affected"
                              ]
                            },
                            {
                              "type": "object",
                              "properties": {
                                "limit": {
                                  "type": "string",
                                  "pattern": "^(0|[a-f0-9]{40}|[a-f0-9]{64})$"
                                }
                              },
                              "required": [
                                "limit"
                              ]
                            }
                          ]
                        }
                      }
                    }
                  }
                },
                {
                  "title": "last_affected and fixed events are mutually exclusive",
                  "if": {
                    "properties": {
                      "events": {
                        "contains": {
                          "required": [
                            "last_affected"
                          ]
                        }
                      }
                    }
                  },
                  "then": {
                    "not": {
                      "properties": {
                        "events": {
                          "contains": {
                            "required": [
                              "fixed"
                            ]
                          }
                        }
                      }
                    }
                  }
                }
              ],
              "required": [
                "type",
                "events"
              ]
            }
          },
          "versions": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "ecosystem_specific": {
            "type": "object"
          },
          "database_specific": {
            "type": "object"
          }
        }
      }
    },
    "references": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "ADVISORY",
              "ARTICLE",
              "DETECTION",
              "DISCUSSION",
              "REPORT",
              "FIX",
              "INTRODUCED",
              "GIT",
              "PACKAGE",
              "EVIDENCE",
              "WEB"
            ]
          },
          "url": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": [
          "type",
          "url"
        ]
      }
    },
    "credits": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "contact": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "type": {
            "type": "string",
            "enum": [
              "FINDER",
              "REPORTER",
              "ANALYST",
              "COORDINATOR",
              "REMEDIATION_DEVELOPER",
              "REMEDIATION_REVIEWER",
              "REMEDIATION_VERIFIER",
              "TOOL",
              "SPONSOR",
              "OTHER"
            ]
          }
        },
        "required": [
          "name"
        ]
      }
    },
    "database_specific": {
      "type": "object"
    }
  },
  "required": [
    "id",
    "modified"
  ],
  "allOf": [
    {
      "if": {
        "required": [
          "severity"
        ]
      },
      "then": {
        "properties": {
          "affected": {
            "items": {
              "properties": {
                "severity": {
                  "type": "null"
                }
              }
            }
          }
        }
      }
    }
  ],
  "$defs": {
    "ecosystemName": {
      "type": "string",
      "title": "Currently supported ecosystems",
      "description": "These ecosystems are also documented at https://ossf.github.io/osv-schema/#affectedpackage-field",
      "enum": [
        "AlmaLinux",
        "Alpaquita",
        "Alpine",
        "Android",
        "Azure Linux",
        "BellSoft Hardened Containers",
        "Bioconductor",
        "Bitnami",
        "Chainguard",
        "CleanStart",
        "ConanCenter",
        "CRAN",
        "crates.io",
        "Debian",
        "Docker Hardened Images",
        "Echo",
        "FreeBSD",
        "GHC",
        "GitHub Actions",
        "Go",
        "Hackage",
        "Hex",
        "Julia",
        "Kubernetes",
        "Linux",
        "Mageia",
        "Maven",
        "MinimOS",
        "npm",
        "NuGet",
        "opam",
        "openEuler",
        "openSUSE",
        "OSS-Fuzz",
        "Packagist",
        "Photon OS",
        "Pub",
        "PyPI",
        "Red Hat",
        "Rocky Linux",
        "Root",
        "RubyGems",
        "SUSE",
        "SwiftURL",
        "TuxCare",
        "Ubuntu",
        "VSCode",
        "Wolfi"
      ]
    },
    "ecosystemSuffix": {
      "type": "string",
      "pattern": ":.+"
    },
    "ecosystemWithSuffix": {
      "type": "string",
      "title": "Currently supported ecosystems",
      "description": "These ecosystems are also documented at https://ossf.github.io/osv-schema/#affectedpackage-field",
      "pattern": "^(AlmaLinux|Alpaquita|Alpine|Android|Azure Linux|BellSoft Hardened Containers|Bioconductor|Bitnami|Chainguard|CleanStart|ConanCenter|CRAN|crates\\.io|Debian|Docker Hardened Images|Echo|FreeBSD|GHC|GitHub Actions|Go|Hackage|Hex|Julia|Kubernetes|Linux|Mageia|Maven|MinimOS|npm|NuGet|opam|openEuler|openSUSE|OSS-Fuzz|Packagist|Photon OS|Pub|PyPI|Red Hat|Rocky Linux|Root|RubyGems|SUSE|SwiftURL|TuxCare|Ubuntu|VSCode|Wolfi|GIT)(:.+)?$"
    },
    "prefix": {
      "type": "string",
      "title": "Currently supported home database identifier prefixes",
      "description": "These home databases are also documented at https://ossf.github.io/osv-schema/#id-modified-fields",
      "pattern": "^(x_|(ASB-A|PUB-A|ALPINE|ALSA|ALBA|ALEA|AZL|BELL|BIT|CGA|CLEANSTART|CLSA|CURL|CVE|DEBIAN|DHI|DRUPAL|DSA|DLA|ELA|DTSA|ECHO|EEF|FreeBSD|GHSA|GO|GSD|HSEC|JLSEC|KUBE|LBSEC|LSN|MAL|MINI|MGASA|OESA|OSEC|OSV|openSUSE-SU|PHSA|PSF|PYSEC|RHBA|RHEA|RHSA|RLSA|RXSA|RSEC|ROOT|RUSTSEC|SUSE-[SRFO]U|UBUNTU|USN|V8)-)"
    },
    "severity": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "CVSS_V2",
              "CVSS_V3",
              "CVSS_V4",
              "Ubuntu"
            ]
          },
          "score": {
            "type": "string"
          },
          "source": {
            "type": "string",
            "enum": [
              "NVD",
              "CNA",
              "SELF"
            ]
          }
        },
        "allOf": [
          {
            "if": {
              "properties": {
                "type": {
                  "const": "CVSS_V2"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "pattern": "^((AV:[NAL]|AC:[LMH]|Au:[MSN]|[CIA]:[NPC]|E:(U|POC|F|H|ND)|RL:(OF|TF|W|U|ND)|RC:(UC|UR|C|ND)|CDP:(N|L|LM|MH|H|ND)|TD:(N|L|M|H|ND)|[CIA]R:(L|M|H|ND))/)*(AV:[NAL]|AC:[LMH]|Au:[MSN]|[CIA]:[NPC]|E:(U|POC|F|H|ND)|RL:(OF|TF|W|U|ND)|RC:(UC|UR|C|ND)|CDP:(N|L|LM|MH|H|ND)|TD:(N|L|M|H|ND)|[CIA]R:(L|M|H|ND))$"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "const": "CVSS_V3"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "pattern": "^CVSS:3[.][01]/((AV:[NALP]|AC:[LH]|PR:[NLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])/)*(AV:[NALP]|AC:[LH]|PR:[NLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])$"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "const": "CVSS_V4"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "pattern": "^CVSS:4[.]0/AV:[NALP]/AC:[LH]/AT:[NP]/PR:[NLH]/UI:[NPA]/VC:[HLN]/VI:[HLN]/VA:[HLN]/SC:[HLN]/SI:[HLN]/SA:[HLN](/E:[XAPU])?(/CR:[XHML])?(/IR:[XHML])?(/AR:[XHML])?(/MAV:[XNALP])?(/MAC:[XLH])?(/MAT:[XNP])?(/MPR:[XNLH])?(/MUI:[XNPA])?(/MVC:[XNLH])?(/MVI:[XNLH])?(/MVA:[XNLH])?(/MSC:[XNLH])?(/MSI:[XNLHS])?(/MSA:[XNLHS])?(/S:[XNP])?(/AU:[XNY])?(/R:[XAUI])?(/V:[XDC])?(/RE:[XLMH])?(/U:(X|Clear|Green|Amber|Red))?$"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "const": "Ubuntu"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "enum": [
                    "negligible",
                    "low",
                    "medium",
                    "high",
                    "critical"
                  ]
                }
              }
            }
          }
        ],
        "required": [
          "type",
          "score"
        ]
      }
    },
    "timestamp": {
      "type": "string",
      "format": "date-time",
      "pattern": "[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+)?Z"
    }
  },
  "additionalProperties": false
}

=== ossf/osv-schema/tools/osv-linter/testdata/CVE-2023-41045.json
{
  "id": "CVE-2023-41045",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N"
    }
  ],
  "details": "Graylog is a free and open log management platform. Graylog makes use of only one single source port for DNS queries. Graylog binds a single socket for outgoing DNS queries and while that socket is bound to a random port number it is never changed again. This goes against recommended practice since 2008, when Dan Kaminsky discovered how easy is to carry out DNS cache poisoning attacks. In order to prevent cache poisoning with spoofed DNS responses, it is necessary to maximise the uncertainty in the choice of a source port for a DNS query. Although unlikely in many setups, an external attacker could inject forged DNS responses into a Graylog's lookup table cache. In order to prevent this, it is at least recommendable to distribute the DNS queries through a pool of distinct sockets, each of them with a random source port and renew them periodically. This issue has been addressed in versions 5.0.9 and 5.1.3. Users are advised to upgrade. There are no known workarounds for this issue.",
  "affected": [
    {
      "ranges": [
        {
          "type": "GIT",
          "repo": "https://github.com/graylog2/graylog2-server",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "466af814523cffae9fbc7e77bab7472988f03c3e"
            },
            {
              "fixed": "a101f4f12180fd3dfa7d3345188a099877a3c327"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/Graylog2/graylog2-server/security/advisories/GHSA-g96c-x7rh-99r3"
    },
    {
      "type": "EVIDENCE",
      "url": "https://github.com/Graylog2/graylog2-server/security/advisories/GHSA-g96c-x7rh-99r3"
    },
    {
      "type": "FIX",
      "url": "https://github.com/Graylog2/graylog2-server/commit/466af814523cffae9fbc7e77bab7472988f03c3e"
    },
    {
      "type": "FIX",
      "url": "https://github.com/Graylog2/graylog2-server/commit/a101f4f12180fd3dfa7d3345188a099877a3c327"
    }
  ],
  "aliases": [
    "GHSA-g96c-x7rh-99r3"
  ],
  "modified": "2023-09-06T20:02:28Z",
  "published": "2023-08-31T18:15:09Z"
}

=== ossf/osv-schema/tools/ghsa/testdata/equals_no_patch.osv.json
{
  "schema_version": "1.5.0",
  "id": "GHSA-4g4c-8gqh-m4vm",
  "aliases": [
    "CVE-2019-13589"
  ],
  "published": "2019-07-16T00:41:55Z",
  "modified": "2021-05-10T22:18:29Z",
  "summary": "Inclusion of Functionality from Untrusted Control Sphere in Ruby",
  "details": "The paranoid2 gem 1.1.6 for Ruby, as distributed on RubyGems.org, included a code-execution backdoor inserted by a third party. The current version, without this backdoor, is 1.1.5.",
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-13589"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-4g4c-8gqh-m4vm"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "RubyGems",
        "name": "paranoid2"
      },
      "ranges": [],
      "versions": [
        "1.1.6"
      ],
      "database_specific": {
        "ghsa": "https://github.com/advisories/GHSA-4g4c-8gqh-m4vm",
        "cwes": [
          {
            "cweId": "CWE-829",
            "description": "The software imports, requires, or includes executable functionality (such as a library) from a source that is outside of the intended control sphere.",
            "name": "Inclusion of Functionality from Untrusted Control Sphere"
          }
        ]
      }
    }
  ]
}

=== ossf/osv-schema/tools/ghsa/testdata/less_than_equals_with_patch.osv.json
{
  "schema_version": "1.5.0",
  "id": "GHSA-f89g-whpf-6q9m",
  "aliases": [
    "CVE-2017-16008"
  ],
  "published": "2018-11-09T17:46:56Z",
  "modified": "2021-01-08T18:53:47Z",
  "summary": "Cross-Site Scripting in i18next",
  "details": "Affected versions of `i18next` allow untrusted user input to be injected into dictionary key names, resulting in a cross-site scripting vulnerability.\n\n## Proof of Concept\n```\nvar init = i18n.init({debug: true}, function(){\n  var test = i18n.t('__firstName__ __lastName__', {\n        escapeInterpolation: true,\n        firstName: '__lastNameHTML__',\n        lastName: '<script>',\n  });\n  console.log(test);\n});\n// equals \"<script> &lt;script&gt;\"\n```\n\n\n## Recommendation\n\nUpdate to version 1.10.3 or later.",
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2017-16008"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-f89g-whpf-6q9m"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "npm",
        "name": "i18next"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.10.3"
            }
          ]
        }
      ],
      "versions": [],
      "database_specific": {
        "ghsa": "https://github.com/advisories/GHSA-f89g-whpf-6q9m",
        "cwes": [
          {
            "cweId": "CWE-79",
            "description": "The software does not neutralize or incorrectly neutralizes user-controllable input before it is placed in output that is used as a web page that is served to other users.",
            "name": "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
          }
        ]
      }
    }
  ]
}

=== ossf/osv-schema/tools/ghsa/testdata/greater_than_equals_no_patch.osv.json
{
  "schema_version": "1.5.0",
  "id": "GHSA-pxmp-fwjc-4x7q",
  "aliases": [],
  "published": "2020-09-03T15:45:23Z",
  "modified": "2020-09-03T15:45:23Z",
  "summary": "HTML Injection in marky-markdown",
  "details": "All versions of `marky-markdown` are vulnerable to HTML Injection due to a validation bypass. The package only allows iframes where the source is `youtube.com` but it is possible to bypass the validation with sources where `youtube.com` is the sub-domain, such as `youtube.com.evil.co`. This \n\n\n## Recommendation\n\nThis package is no longer maintained. Please upgrade to `@npmcorp/marky-markdown`",
  "references": [
    {
      "type": "WEB",
      "url": "https://www.npmjs.com/advisories/1471"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-pxmp-fwjc-4x7q"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "npm",
        "name": "marky-markdown"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0.0.0"
            }
          ]
        }
      ],
      "versions": [],
      "database_specific": {
        "ghsa": "https://github.com/advisories/GHSA-pxmp-fwjc-4x7q",
        "cwes": []
      }
    }
  ]
}

=== ossf/osv-schema/tools/vuxml/testdata/VUXML/CVE-2025-3454.json
{
    "schema_version": "1.2.0",
    "id": "310f5923-211c-11f0-8ca6-6c3be5272acd",
    "modified": "2025-04-24T00:00:00Z",
    "published": "2025-04-24T00:00:00Z",
    "summary": "Grafana -- Authorization bypass in data source proxy API",
    "details": "\n\t\n\tGrafana Labs reports:\n\t\n\t  This vulnerability, which was discovered while reviewing a pull\n\t  request from an external contributor, effects Grafana\u2019s data source\n\t  proxy API and allows authorization checks to be bypassed by adding\n\t  an extra slash character (/) in the URL path. Among Grafana-maintained\n\t  data sources, the vulnerability only affects the read paths\n\t  of Prometheus (all flavors) and Alertmanager when configured with\n\t  basic authorization.\n\t  The CVSS score for this vulnerability is\n\t  5.0 MEDIUM.\n\t\n\t\n    \n    ",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://api.osv.dev/v1/vulns/CVE-2025-3454"
        },
        {
            "type": "WEB",
            "url": "https://grafana.com/blog/2025/04/22/grafana-security-release-medium-and-high-severity-fixes-for-cve-2025-3260-cve-2025-2703-cve-2025-3454/"
        }
    ],
    "affected": [
        {
            "package": {
                "ecosystem": "FreeBSD:ports",
                "name": "grafana"
            },
            "ranges": [
                {
                    "type": "SEMVER",
                    "events": [
                        {
                            "introduced": "8.0.0"
                        },
                        {
                            "fixed": "10.4.17+security-01"
                        }
                    ]
                },
                {
                    "type": "SEMVER",
                    "events": [
                        {
                            "introduced": "11.0.0"
                        },
                        {
                            "fixed": "11.2.8+security-01"
                        }
                    ]
                },
                {
                    "type": "SEMVER",
                    "events": [
                        {
                            "introduced": "11.3.0"
                        },
                        {
                            "fixed": "11.3.5+security-01"
                        }
                    ]
                },
                {
                    "type": "SEMVER",
                    "events": [
                        {
                            "introduced": "11.4.0"
                        },
                        {
                            "fixed": "11.4.3+security-01"
                        }
                    ]
                },
                {
                    "type": "SEMVER",
                    "events": [
                        {
                            "introduced": "11.5.0"
                        },
                        {
                            "fixed": "11.5.3+security-01"
                        }
                    ]
                },
                {
                    "type": "SEMVER",
                    "events": [
                        {
                            "introduced": "11.6.0"
                        },
                        {
                            "fixed": "11.6.0+security-01"
                        }
                    ]
                }
            ]
        },
        {
            "package": {
                "ecosystem": "FreeBSD:ports",
                "name": "grafana8"
            },
            "ranges": [
                {
                    "type": "SEMVER",
                    "events": [
                        {
                            "introduced": "8.0.0"
                        }
                    ]
                }
            ]
        },
        {
            "package": {
                "ecosystem": "FreeBSD:ports",
                "name": "grafana9"
            },
            "ranges": [
                {
                    "type": "SEMVER",
                    "events": [
                        {
                            "introduced": "9.0.0"
                        }
                    ]
                }
            ]
        }
    ],
    "database_specific": {
        "discovery": "2025-03-25T00:00:00Z"
    }
}
